In [10]:
import pandas as pd
from custom_knn_algorithm import Custom_KNN_Classifier
from knn_algorithm import KNN_classifier
import numpy as np
from sklearn.model_selection import train_test_split

In [9]:
df = pd.read_csv("/home/alex/Documents/GitHub/ML-Group126/datasets/StudentsPerformance.csv")


print(df.shape)
df.head()

(1000, 8)


gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [28]:
train_x, test_x, train_y, test_y = train_test_split(df[["math score", "reading score", "writing score"]], df["test preparation course"], test_size=0.2)

train = np.column_stack((train_x, train_y))

knn = KNN_classifier(k=10)
knn.feed_data(train)

test_x = test_x.values
test_y = test_y.values

<class 'numpy.ndarray'>


In [32]:
predictions = []

print(test_x[:5])
print(train[:5])
for test in test_x:
    predictions.append(knn.predict(knn.predict(test)))
    
true = 0
false = 0
index = 0

while index != len(predictions):
    if predictions[index] == test_y[index]:
        true +=1
    else:
        false -=1
    
    index +=1
    
    print(f"the accuracy is {round(true/(false+true), 2)} with {true} correct and {false} incorrect classifications")

[[72 57 62]
 [67 80 81]
 [53 52 49]
 [40 48 50]
 [60 68 72]]
[[82 93 93 'none']
 [57 67 72 'none']
 [53 44 42 'none']
 [69 60 63 'completed']
 [66 74 81 'completed']]


DimensionalityError: (DimensionalityError(...), "The dimensionality of the prediction point doesn't match the dimensionality of the dataset!")